apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-gh

images:
  - name: minicommerce/.azurecr.io//azure-vote-front
    newTag: a6a73eb69a3589c74e6c47af5bebcc190cd6f30f
  - name: minicommerce/.azurecr.io//azure-vote-back
    newTag: a6a73eb69a3589c74e6c47af5bebcc190cd6f30f
resources:
  - manifests.yaml